name: Test Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout adimi
        uses: actions/checkout@v4

      - name: Environment variable listeleme
        run: printenv
